// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: api/clients/face_recognizer.proto

package face_recognizer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecognizeFaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Face *Face `protobuf:"bytes,1,opt,name=face,proto3" json:"face,omitempty"`
}

func (x *RecognizeFaceRequest) Reset() {
	*x = RecognizeFaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_clients_face_recognizer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognizeFaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeFaceRequest) ProtoMessage() {}

func (x *RecognizeFaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clients_face_recognizer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeFaceRequest.ProtoReflect.Descriptor instead.
func (*RecognizeFaceRequest) Descriptor() ([]byte, []int) {
	return file_api_clients_face_recognizer_proto_rawDescGZIP(), []int{0}
}

func (x *RecognizeFaceRequest) GetFace() *Face {
	if x != nil {
		return x.Face
	}
	return nil
}

type RecognizeFaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonName   string        `protobuf:"bytes,1,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`
	FaceLocation *FaceLocation `protobuf:"bytes,2,opt,name=face_location,json=faceLocation,proto3" json:"face_location,omitempty"`
}

func (x *RecognizeFaceResponse) Reset() {
	*x = RecognizeFaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_clients_face_recognizer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognizeFaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeFaceResponse) ProtoMessage() {}

func (x *RecognizeFaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_clients_face_recognizer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeFaceResponse.ProtoReflect.Descriptor instead.
func (*RecognizeFaceResponse) Descriptor() ([]byte, []int) {
	return file_api_clients_face_recognizer_proto_rawDescGZIP(), []int{1}
}

func (x *RecognizeFaceResponse) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *RecognizeFaceResponse) GetFaceLocation() *FaceLocation {
	if x != nil {
		return x.FaceLocation
	}
	return nil
}

type TrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Face       *Face  `protobuf:"bytes,1,opt,name=face,proto3" json:"face,omitempty"`
	PersonName string `protobuf:"bytes,2,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_clients_face_recognizer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clients_face_recognizer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_api_clients_face_recognizer_proto_rawDescGZIP(), []int{2}
}

func (x *TrainRequest) GetFace() *Face {
	if x != nil {
		return x.Face
	}
	return nil
}

func (x *TrainRequest) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

type Face struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Face) Reset() {
	*x = Face{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_clients_face_recognizer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Face) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Face) ProtoMessage() {}

func (x *Face) ProtoReflect() protoreflect.Message {
	mi := &file_api_clients_face_recognizer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Face.ProtoReflect.Descriptor instead.
func (*Face) Descriptor() ([]byte, []int) {
	return file_api_clients_face_recognizer_proto_rawDescGZIP(), []int{3}
}

func (x *Face) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FaceLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left   uint32 `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Top    uint32 `protobuf:"varint,2,opt,name=top,proto3" json:"top,omitempty"`
	Right  uint32 `protobuf:"varint,3,opt,name=right,proto3" json:"right,omitempty"`
	Bottom uint32 `protobuf:"varint,4,opt,name=bottom,proto3" json:"bottom,omitempty"`
}

func (x *FaceLocation) Reset() {
	*x = FaceLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_clients_face_recognizer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceLocation) ProtoMessage() {}

func (x *FaceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_clients_face_recognizer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceLocation.ProtoReflect.Descriptor instead.
func (*FaceLocation) Descriptor() ([]byte, []int) {
	return file_api_clients_face_recognizer_proto_rawDescGZIP(), []int{4}
}

func (x *FaceLocation) GetLeft() uint32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *FaceLocation) GetTop() uint32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *FaceLocation) GetRight() uint32 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *FaceLocation) GetBottom() uint32 {
	if x != nil {
		return x.Bottom
	}
	return 0
}

var File_api_clients_face_recognizer_proto protoreflect.FileDescriptor

var file_api_clients_face_recognizer_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x66, 0x61,
	0x63, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x31, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x46, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x66, 0x61, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x52, 0x04, 0x66,
	0x61, 0x63, 0x65, 0x22, 0x6c, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65,
	0x46, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a,
	0x0d, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x66, 0x61, 0x63, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x4a, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x04, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x52, 0x04, 0x66, 0x61, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a,
	0x04, 0x46, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x62, 0x0a, 0x0c, 0x46, 0x61, 0x63,
	0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x6f, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x32, 0x84, 0x01,
	0x0a, 0x0e, 0x46, 0x61, 0x63, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x72,
	0x12, 0x40, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x46, 0x61, 0x63,
	0x65, 0x12, 0x15, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x46, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x67,
	0x6e, 0x69, 0x7a, 0x65, 0x46, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x30, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_clients_face_recognizer_proto_rawDescOnce sync.Once
	file_api_clients_face_recognizer_proto_rawDescData = file_api_clients_face_recognizer_proto_rawDesc
)

func file_api_clients_face_recognizer_proto_rawDescGZIP() []byte {
	file_api_clients_face_recognizer_proto_rawDescOnce.Do(func() {
		file_api_clients_face_recognizer_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_clients_face_recognizer_proto_rawDescData)
	})
	return file_api_clients_face_recognizer_proto_rawDescData
}

var file_api_clients_face_recognizer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_clients_face_recognizer_proto_goTypes = []interface{}{
	(*RecognizeFaceRequest)(nil),  // 0: RecognizeFaceRequest
	(*RecognizeFaceResponse)(nil), // 1: RecognizeFaceResponse
	(*TrainRequest)(nil),          // 2: TrainRequest
	(*Face)(nil),                  // 3: Face
	(*FaceLocation)(nil),          // 4: FaceLocation
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_api_clients_face_recognizer_proto_depIdxs = []int32{
	3, // 0: RecognizeFaceRequest.face:type_name -> Face
	4, // 1: RecognizeFaceResponse.face_location:type_name -> FaceLocation
	3, // 2: TrainRequest.face:type_name -> Face
	0, // 3: FaceRecognizer.RecognizeFace:input_type -> RecognizeFaceRequest
	2, // 4: FaceRecognizer.Train:input_type -> TrainRequest
	1, // 5: FaceRecognizer.RecognizeFace:output_type -> RecognizeFaceResponse
	5, // 6: FaceRecognizer.Train:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_clients_face_recognizer_proto_init() }
func file_api_clients_face_recognizer_proto_init() {
	if File_api_clients_face_recognizer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_clients_face_recognizer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecognizeFaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_clients_face_recognizer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecognizeFaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_clients_face_recognizer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_clients_face_recognizer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Face); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_clients_face_recognizer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaceLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_clients_face_recognizer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_clients_face_recognizer_proto_goTypes,
		DependencyIndexes: file_api_clients_face_recognizer_proto_depIdxs,
		MessageInfos:      file_api_clients_face_recognizer_proto_msgTypes,
	}.Build()
	File_api_clients_face_recognizer_proto = out.File
	file_api_clients_face_recognizer_proto_rawDesc = nil
	file_api_clients_face_recognizer_proto_goTypes = nil
	file_api_clients_face_recognizer_proto_depIdxs = nil
}
